//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBorrowHistory
    {
        public int BorrowHistoryId { get; set; }
        public Nullable<int> bookId { get; set; }
        public Nullable<int> memberId { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual tblBook tblBook { get; set; }
        public virtual tblMember tblMember { get; set; }
    }
}
